package internal

type AutoGenerated struct {
	Status string `json:"status"`
	Result struct {
		Items []struct {
			Images struct {
				Main []struct {
					URL       string `json:"url"`
					ColorCode string `json:"colorCode"`
				} `json:"main"`
			} `json:"images"`
			Name   string `json:"name"`
			Prices struct {
				Base struct {
					Currency struct {
						Code   string `json:"code"`
						Symbol string `json:"symbol"`
					} `json:"currency"`
					Value string `json:"value"`
				} `json:"base"`
				Promo struct {
					Currency struct {
						Code   string `json:"code"`
						Symbol string `json:"symbol"`
					} `json:"currency"`
					Value string `json:"value"`
				} `json:"promo"`
			} `json:"prices"`
			ProductID string `json:"productId"`
		} `json:"items"`
		Pagination struct {
			Count  int `json:"count"`
			Total  int `json:"total"`
			Offset int `json:"offset"`
		} `json:"pagination"`
	} `json:"result"`
}
