name: Run

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    run:
      description: 'Run workflow'
      required: true
      type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Run the script
        run: go run main.go

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commited_message: Update fetched item
